### ISSUE TITLE
Add c2c

### ISSUE THREAD

**Issue by eelregit** [rainwoodman/pmesh#30] opened 2018-02-07 03:28 UTC
would be possible? For example it would make things like the ConvolvedPower in nbodykit easier.

**Comment by rainwoodman** [comment] 2018-02-11 00:22
Is it because you want to pack two real fields into a single complex field?

**Comment by eelregit** [comment] 2018-02-11 00:43
FFT of spherical harmonics weighted density field as an example. Just more
convenient to do with a c2c method.

**Comment by eelregit** [comment] 2018-02-11 00:59
Hmmm... really_complex? ;)

**Comment by rainwoodman** [comment] 2018-02-11 01:02
I think the problem is that ComplexField shall be renamed to
HermitianField.

**Comment by eelregit** [comment] 2018-02-11 01:24
Good point.

**Comment by rainwoodman** [comment] 2018-05-19 01:14
The branch is merged.

**Closed by rainwoodman** 2018-05-19 01:14 UTC
